### ISSUE TITLE
record data

### ISSUE THREAD

**Issue by montoyamoraga** [vanevery/kinectron#5]
way of recording skeleton data as json file in order to playback later?

**Comment by lisajamhoury** [comment]
We don't have a way of doing this, and it's not currently in the pipeline. Maybe look into a library that does just this? Maybe something like node-replay could help?

**Comment by vanevery** [comment]
It's a great idea and very useful for a lot of purposes!  Pull requests welcome ;-)

**Comment by vanevery** [comment]
ps.  If you want to try, let's meet, I can give you a head start (I have some example code)

**Comment by lisajamhoury** [comment]
@montoyamoraga FYI we added record functionality for skeleton to json and the image frames to webm in release 0.0.4.8 https://github.com/lisajamhoury/kinectron/releases/tag/0.0.4.8
